### ISSUE TITLE
Example Table component fails to render data

### ISSUE THREAD

**Issue by oakley808** [NuCivic/react-dash#29]
When I run either the dashboard with `npm start` or the boilerplate dashboard with `npm run dev_standalone` I fail to get any data in the table component.  The fetch appears to work and the console doesn't show any relevant errors.  
Is there a running demo somewhere?
I'm running node 6.2 and react 15.

**Comment by topicus** [comment]
I'll take a look.

**Comment by oakley808** [comment]
Thanks. 
On the boilerplate app (https://github.com/NuCivic/react-dashboard-boilerplate) all the components with remote calls for data fail to render anything. So maybe it's not the table component specifically that's not working.

**Comment by topicus** [comment]
Sorry @oakley808 I've been pretty slammed these weeks. I'll take a look at this soon.

**Comment by oakley808** [comment]
Ok. Thanks. I've also noticed in your demo, ```getCustomData()``` in GAChart.js seems to fire four times for every chart. Maybe calling ```getData()``` from its render function is updating state and causing a re-render, and re-fetch? I'm not quite clear on where the loop is.

**Comment by oakley808** [comment]
So I'd love to contribute to this project. Do you have any guidelines or requirements for pull requests?

**Comment by topicus** [comment]
@oakley808 Great to hear that! We don't have guidelines yet because this project it's in a very early stage. 

I can share with you what's our roadmap:

- Identify components requiring react lifecycle hooks. (e.g. to load data)
- Move to stateless components when lifecycle hooks are not needed
- Replace inheritance with high-order components 
(https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775)
- Move to redux architecture (require previews steps done)
- Allow dashboards creation using just jsx. So we integrate layout creation an configuration in a single step.
- Save dashboards states in a redux store. So we will be able to save dashboard snapshots in a json object. 
- Create store enhancers to adapt data to thirty party libraries. Some libraries needs data in a certain way so we need to create common transformations to simplify dashboard development process as possible.

I think that's it.

@starsinmypockets

**Comment by oakley808** [comment]
That's great. I think moving to redux will be a big win.
If you would identify the components that don't need lifecycle hooks I can
transition them to stateless functional components. Would that be a
reasonable place to start?

On Tue, Aug 16, 2016 at 8:40 AM, Mariano Carballal <notifications@github.com

**Comment by starsinmypockets** [comment]
@oakley808 @topicus 

Any component should be a candidate. Without shifting the entire architecture redux, it's not exactly clear to me where the application state will be store (as an interim measure).

In the redux model the state will be stored in the store, of course, and update by actions/reducers.

If you have an idea of an interim solution, have a stab at it and submit a pull request!

Also, you guys should note that I did make some inroads to a redux architecture here 
https://github.com/NuCivic/react-dashboard/pull/27/commits/d7efe0a8e820b73fb74373a2b06260e0d91ba402

This uses a factory function to create the dashboard using the settings object, where the settings object is represented in the redux store. I believe that this would be a decent starting place for the redux implementation.

**Comment by topicus** [comment]
I think @starsinmypockets find the reason for the bug in the table component @oakley808

**Comment by topicus** [comment]
@starsinmypockets Do you know if this was fixed?

**Comment by starsinmypockets** [comment]
@oakley808 Check out (co) the 0.5.x branch it's not redux but it has a single-state architecture that I think is close enough for now.
